name: Schedule Tweet

on:
  schedule:
    - cron: '30 18 * * *'

  # Allows you to manually run the workflow from the GitHub Actions tab
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tweepy python-dotenv

    - name: Run tweet script
      env:
        API_KEY: ${{ secrets.API_KEY }}
        API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        RELEASE_DATE: '2025-08-09'
      run: |
        python tweet.py
